### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by ziutek** [defunkt/pystache#10]
Pystache doesn't work with strings encoded in non ascii encoding.

There is template_encoding variable that permits write templates in any encoding but there isn't such variable for strings generated by application.

In template.py file, in render_tag and  render_unescaped functions there is unicode() function called without second parameter - the default encoding (ascii) is assumed even if string passed to it is UTF-8 encoded.

**Comment by defunkt** [comment]
Do you know what we should do to fix this?

**Comment by ziutek** [comment]
My proposal:
1. Defining application_encoding variable in View class (similar to template_encoding variable) with default value from sys.getdefaultencoding().
2. Defining application_encoding variable in Template class with default value from sys.getdefaultencoding() (Template.__init__(...) method must be modified for properly set it).
3. In Template.render_tag(...) changing
   return cgi.escape(unicode(raw))
   to
   return cgi.escape(unicode(raw, self.application_encoding))
4. In Template.render_unescaped(...) changing
   return unicode(get_or_attr(context, tag_name, ''))
   to
   return unicode(get_or_attr(context, tag_name, ''), self.application_encoding)
5. In View.render(...) changing
   return Template(template, self).render(encoding=encoding)
   to
   return Template(template, self, self.application_encoding).render(encoding=encoding)

**Comment by cjerdonek** [comment]
I also think we should ensure that incoming template strings are unicode strings (converting them if necessary using the encoding above), and generally do everything in unicode in the Template class.  Currently, we're mixing byte strings and unicode strings which doesn't make for a great situation.  We probably also want to support [`unicode()`'s `errors` parameter](http://docs.python.org/library/functions.html#unicode) eventually.

It may be possible to have an encoding-unaware implementation that operates on everything as byte strings, but I'm not sure that's a use case worth supporting -- at least at this point.

**Comment by cjerdonek** [comment]
FYI, this has been implemented in the development branch for the Template class -- but not yet for Views.

**Comment by cjerdonek** [comment]
This is now also supported for views in the development branch via the new [`renderer.render(view)`](https://github.com/defunkt/pystache/blob/7e0270b0dac540e17c020d2eefec6fb82099bf18/tests/test_renderer.py#L403) syntax.  Pass the encoding behavior to the Renderer instance via the [`default_encoding` and `decode_errors`](https://github.com/defunkt/pystache/blob/7e0270b0dac540e17c020d2eefec6fb82099bf18/pystache/renderer.py#L44) keyword arguments when constructing (or set the attributes after constructing).
