### ISSUE TITLE
View executes callables wrongly

### ISSUE THREAD

**Issue by rafacv** [defunkt/pystache#11]
View class always executes callable variables, it doesn't matter if it's a view's method or a lambda in the context dictionary.
Bug can be spotted by running the code in the following gist:
http://gist.github.com/522505

I wrote a test and code to fix it, as you can see in this compare view:
http://github.com/rafaelcv/pystache/compare/defunkt:49c34b...view_callable_bug

**Comment by cjerdonek** [comment]
Using `git-bisect`, it looks like this was fixed back in Dec. 2010 by [this commit](https://github.com/defunkt/pystache/commit/5f35d312486ed49ebb6a4039cbc21328571263d9).  It still seems to be fixed.

I will make sure we have a test case covering this issue before closing this issue.
