### ISSUE TITLE
Release v0.5.3 to PyPI

### ISSUE THREAD

**Issue by cjerdonek** [defunkt/pystache#119]
See [HISTORY](https://github.com/defunkt/pystache/blob/development/HISTORY.md) for changes.

**Comment by sontek** [comment]
This should probably happen ;)   I would like #130 fixed before then though

**Comment by cjerdonek** [comment]
Sorry. :) I'll make an effort to do the release by this weekend, or the weekend after that at the very latest (the latter more likely if the resolution for issue #130 isn't clear).

I'll also respond to issue #130 tomorrow or later today.

**Comment by cjerdonek** [comment]
This has obviously taken longer than I had hoped. :)

I believe the preparations are largely done now and the outstanding issues (for this version) addressed.  I will merge development to master soon to create a 0.5.3 release candidate.

**Comment by cjerdonek** [comment]
The 0.5.3 release candidate is now in branch master.  I'm going to let it sit for at least a week or two before pushing to PyPI.

**Comment by sontek** [comment]
Awesome!  At least its getting there :)

**Comment by cjerdonek** [comment]
This is now done.

**Comment by boukeversteegh** [comment]
How do I customize Renderer to output None as ""? Can't find the commit..

**Comment by boukeversteegh** [comment]
Figured it out:

```
class MyRenderer(pystache.Renderer):
    def str_coerce(self, val):
        return str(val) if val else ""

renderer = MyRenderer()
renderer.render('<input value="{value}"/>', {"value":None})
```
