### ISSUE TITLE
Add Renderer.render_name()

### ISSUE THREAD

**Issue by cjerdonek** [defunkt/pystache#122]
The `Renderer` class currently lets one render a template given a template string, object instance, or path (via the `render()` and `render_path()` methods respectively), but it does not let one render a template by name directly (using the `search_dirs` attribute, etc).

We should add `Renderer.render_name()`.

**Comment by jakearchibald** [comment]
+1

**Comment by cjerdonek** [comment]
Committed in the development branch.
