### ISSUE TITLE
Dotted name don't work with object's __getitem__

### ISSUE THREAD

**Issue by x86-64** [defunkt/pystache#123]
If i define object with **getitem** i can not print variable from template with dotted name ({{obj.attr}}.
I've stopped on this hack which helped me, however i don't really know how to do this right.

<pre>
 43     if isinstance(context, dict):
 44         # Then we consider the argument a "hash" for the purposes of the spec.
 45         #
 46         # We do a membership test to avoid using exceptions for flow control
 47         # (e.g. catching KeyError).
 48         if key in context:
 49             return context[key]
 50     else:
 51         try:
 52             attr = context[key]
 53         except AttributeError, e:
 54             return _NOT_FOUND
 55         except TypeError, e:
 56                 try:
 57                     attr = getattr(context, key)
 58                 except AttributeError, e:
 59                     return _NOT_FOUND
 60         if callable(attr):
 61             return attr()
 62         return attr
 63     return _NOT_FOUND
</pre>

**Comment by cjerdonek** [comment]
Hi @x86-64 and thanks for the report.  The beginning of [this page](https://github.com/mustache/spec/blob/master/specs/interpolation.yml) from the Mustache spec would be good to review for discussion purposes.

A couple questions:

Would you prefer that your object be interpreted as a hash or as an object for the purposes of the spec?  In particular, are all of your object's context attributes accessed via `__getitem__` or are some of them accessed as methods/attributes, too?

Strictly speaking, the spec says that the value of an attribute for an object is "the value returned by the method with the given name," which is different from calling `__getitem__` in Python-land.  Would you consider implementing [`__getattr__`](http://docs.python.org/reference/datamodel.html#object.__getattr__) for your objects (or perhaps [`__getattribute__`](http://docs.python.org/reference/datamodel.html#object.__getattribute__)) -- and having that method call `__getitem__`?  It seems like that might work to solve your problem in a way that's unambiguously consistent with the spec.

**Comment by x86-64** [comment]
All attributes that i access from mustache template is processed by 
`__getitem__`. Well, i could add those methods for each attribute, but 
this is what i was trying to avoid by using getitem in first place. 
Isn't getitem could be considered as special catch-all attribute? 
Because obj["attr"] in python works, and i was expecting that 
{{obj.attr}} would work too, despite on how it was implemented. Maybe i 
missing something here.

**Comment by cjerdonek** [comment]
I wasn't suggesting adding those methods for each attribute.  I was suggesting doing this, for example (using `__getattr__` instead of or in addition to  `__getitem__`):

```
class MyClass(object):

    def __init__(self, data):
        self.data = data

    def __getitem__(self, key):
        return self.data[key]

    def __getattr__(self, name):
        return self.__getitem__(name)  # or alternatively, return self.data[key]

foo = MyClass({'bar': 'baz'})

# Now these both work
print foo['bar']
print foo.bar
```

Would this work for you?

**Comment by x86-64** [comment]
Oh, i've tested this, but it fails then it call any of other methods. 
(In my case this is "user" class, where i have general functions, like 
save(), load() and other attributes is user's parameters). So i need 
either to add my parameters to list inside **getattr**, or list of 
methods. Is this right, or there is another way?
Anyway i've noticed that this case fall into "return _NOT_FOUND", so i 
this there would be not much harm to add one more check with "try".

**Comment by cjerdonek** [comment]
I'm not sure what you mean when you say "but it fails to call any of the other methods."  As the Python documentation linked to above says, `__getattr__` is "called [only] when an attribute lookup has not found the attribute in the usual places."  This means that `__getattr__` is called only as a _backup_ after first trying to call a method or attribute with that name.

Here is some sample code to show that it works.

https://gist.github.com/2977954

So you would not need to add your methods to a list inside `__getattr__` for this to work.

**Comment by x86-64** [comment]
Oh, it was stupid mistake, i had "class User:", and should be "class 
User(object)". Sorry for bothering, we can close this. Thanks for help.

**Comment by cjerdonek** [comment]
No problem!  Thanks for using Pystache, and glad it worked out in the end.

**Comment by SamJoan** [comment]
Crazy, defining the models as `class Model(object)` instead of `class Model()` allowed me to access the attributes from pystache.

**Comment by aafaq146** [comment]
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    api = TwitterClient('Afridi')
  File "C:\Users\Aafaq Ahmad\Aafaq Sahib\twitter.py", line 16, in __init__
    consumer_key = os.environ['JQM5TMwSPV6fKHmfbSBNKgE2O']
  File "C:\Users\Aafaq Ahmad\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'JQM5TMwSPV6fKHmfbSBNKgE2O'

plz hep me toresolve this issue
