### ISSUE TITLE
mustache template variables with dot fail to 'render'

### ISSUE THREAD

**Issue by akkumar** [defunkt/pystache#141]
Eg:

<pre><code>
>>> mydict
{'catalina_home': '/opt/software/tomcat7', 'catalina.home': '/opt/software/tomcat7'}
>>> pystache.render('Hello {{catalina.home}}', mydict)
u'Hello '
</code></pre>

Not sure if  this is  a limitation / against the mustache template language grammar or 
 an issue with pystache implementation.

**Comment by cjerdonek** [comment]
It's not a limitation but a feature. :grinning:  The latest versions of Pystache support "dot notation" which you can read about [here](https://github.com/mustache/spec/blob/master/specs/interpolation.yml), for example.

**Comment by akkumar** [comment]
So , I installed pystache 0.5.3 , using 

<pre>
# pip install pystache 
</pre>

on my Ubuntu box.  Seems to bring in 0.5.3 . 

When you mean "latest versions of pystache support dot notation" , where can I get the ones that support it ( may be the github master ? ) . Any publicly available package for the same.

**Comment by cjerdonek** [comment]
You can see in the HISTORY file that support for dot notation was added in version 0.5.2.  Note: "support for dot notation" means that dots have special meaning.  In other words, in version 0.5.2 onwards you are not allowed to have a plain tag/key name with a dot in it; a dot results in special behavior described in the link I referenced above.

**Comment by akkumar** [comment]
Thanks, chris. 

Dot notation is well-supported in 0.5.3 pystache as well. 

It requires a different dictionary structure with the dot notation though.  FYI, for reference: 

<pre><code>
>>> mydict
{'catalina': {'home': '/opt/software/tomcat7'} }
>>> pystache.render('Hello {{catalina.home}}', mydict)
u'Hello /opt/software/tomcat7'
</code></pre>
