### ISSUE TITLE
not correctly handling 'Non-False Values'

### ISSUE THREAD

**Issue by breathe** [defunkt/pystache#15]
pystache doesn't implement the behavior for 'Non-False Values' described in the mustache 'spec':

[1]http://mustache.github.com/mustache.5.html

Example from spec page:

Template:

{{#person?}}
  Hi {{name}}!
{{/person?}}
Hash:

{
  "person?": { "name": "Jon" }
}
Output:

Hi Jon!

pystache iterates over the keys of the {"name": "Jon"} object -- this gives an error as the string object "name" has no get lookup method.  The behavior is the same as one would get by passing in this context:

{
  "person?": ["name"]
}

**Comment by breathe** [comment]
Apologies as this has been fixed in the git branch -- problem still exists in most recent release version though.

**Comment by cjerdonek** [comment]
This indeed isn't an issue in the current master branch, but I will make sure this case is covered by our unit tests before closing this issue.

**Comment by cjerdonek** [comment]
For future reference, using `git-bisect`, it looks like this was fixed back in May 2010 in [this commit](https://github.com/defunkt/pystache/commit/3bcd6b632c3bed0a99ed2b18516dd17f395ede73).
