### ISSUE TITLE
Python 3 classifiers

### ISSUE THREAD

**Issue by hwkns** [defunkt/pystache#163]
Does pystache officially support Python 3?

If so, it would be nice to designate that on PyPI using classifiers in setup.py (see https://pypi.python.org/pypi?%3Aaction=list_classifiers)

If not, what does the path forward look like?

**Comment by cjerdonek** [comment]
Yes, it does.  Did you [look](https://github.com/defunkt/pystache/blob/master/setup.py#L138)?  It's also mentioned in the README.

**Comment by hwkns** [comment]
Well now I feel like an idiot.  I did look, but it's quite a large file and I must have been looking in the wrong place.

I did see the README documentation, and that is why I asked "officially" -- I know a lot of libs that have been tinkering with python 3 for a while but do not have fully passing test suites yet or for whatever other reason they have intentionally left python 3 classifiers out of PyPI.

I suppose my question now is, since setup.py was last updated on May 9, and the newest PyPI release was uploaded on May 12, why are the classifiers not there?

**Comment by cjerdonek** [comment]
Hmm, I'm not sure.  They show for the [previous release 0.5.3](https://pypi.python.org/pypi/pystache/0.5.3), which I uploaded.  I didn't upload the last release, though, so I don't know if something different was done that time.  Instructions for pushing to PyPI are [here](https://github.com/defunkt/pystache/blob/master/setup.py#L45).

I would file a separate issue for that: "Trove Classifiers not showing up on PyPI."

**Comment by hwkns** [comment]
Done: https://github.com/defunkt/pystache/issues/164.  Sorry I wasn't more thorough the first time around.
