### ISSUE TITLE
Trove Classifiers not showing up on PyPI

### ISSUE THREAD

**Issue by hwkns** [defunkt/pystache#164]
The classifiers are present in `setup.py`:
https://github.com/defunkt/pystache/blob/master/setup.py#L138

They show up in the previous release:
https://pypi.python.org/pypi/pystache/0.5.3

But not the current release:
https://pypi.python.org/pypi/pystache/0.5.4

**Comment by cjerdonek** [comment]
Okay, I reregistered the package metadata for the release by reuploading the `PKG-INFO` file through the PyPI web interface.  I think it should be fixed now.  Please reopen this issue if you notice something else amiss.   Thanks for the report!
