### ISSUE TITLE
pystache.render() with special characters

### ISSUE THREAD

**Issue by eddpascoal** [defunkt/pystache#168]
i'm getting a very annoying problem with pystache using special characters.. :(

How can i render the follow example:
import pystache
new_render = pystache.Renderer()
example = new_render.render("person:{{name}}", {"name":"João"})

Anyone have any idea how to lead with special characters using pystache? when i try to run this 'example' it occurs me a UnicodeDecodeError:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)

**Comment by cjerdonek** [comment]
Can you copy the entire Python file to a gist so we can see it?

**Comment by cjerdonek** [comment]
Also, are you using Python 2 or 3?

**Comment by eddpascoal** [comment]
Hi cjerdonek yes im  using Python 2.7 in windows with netbeans IDE 7.4 

python example is pretty much what i'm showing in example as you will find in https://gist.github.com/MrZogs/6a31e9daf110ea84a414

**Comment by cjerdonek** [comment]
I would recommend reading up on Unicode and Python, etc.  This is partly an issue with familiarizing yourself with how Python handles such strings.

Try this in your code (also note the declaration for Python of a source code encoding):

```
# encoding: utf8

import pystache
weird_json ={"person": "JoÃ£o"}
new_render = pystache.Renderer(string_encoding='utf8')
print new_render.render("Hi {{person}}!", weird_json)
```

This worked for me.

Also, even better would be to use Unicode strings as your input instead of byte strings:

```
# encoding: utf8

import pystache
weird_json ={"person": u"JoÃ£o"}
new_render = pystache.Renderer()
print new_render.render("Hi {{person}}!", weird_json)
```

This also worked for me.

**Comment by eddpascoal** [comment]
Right, it works! I read a few things about unicode. I try to run that in Netbeans IDE and it occurs me: 
"UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 5: ordinal not in range(128)"
but when i run it on the cmd.exe with python it works fine. I think it is an IDE misconfiguration issue. 

Thanks a lot for your help.

**Comment by cjerdonek** [comment]
Okay, cool.  Glad to be of help.

**Comment by eddpascoal** [comment]
Just to help others with the same problem about using a Netbeans IDE for python. I found a Netbeans bug comment about python encoding that may be help. See in: https://netbeans.org/bugzilla/show_bug.cgi?id=171688 . For this reason i may change my IDE to work with.
