### ISSUE TITLE
Special characters not rendering.

### ISSUE THREAD

**Issue by anickle** [defunkt/pystache#174]
I have a mustache template that I render in a Django project using pystache's Renderer. Some of the mustache strings contain html entities, but the renderer replaces the `&` character with `&amp;`, which breaks the html entities. How do you get around this?

**Comment by cjerdonek** [comment]
HTML escaping occurs by default.  You can get around this by using triple delimiters for literal rendering, e.g. `{{{name}}}`.  See the man page referenced in the README for more details.

**Comment by anickle** [comment]
Thanks a million; that works.
