### ISSUE TITLE
Template loading case sensitive issue

### ISSUE THREAD

**Issue by joshthecoder** [defunkt/pystache#2]
I noticed this issue when I went to run the nose tests on linux. Pystache attempts to load the template using the View's class name, which is usually capitalized. This creates a problem on case sensitive OS's (like linux) and it will complain about not finding the template file (which in the tests case is called simple.mustache, not Simple.mustache).

Here's a small fix that lower cases the class name before attempting to load the template.

http://gist.github.com/226741

**Comment by defunkt** [comment]
Add failing (but almost passing) ComplexView test. Closed by d68ae32fdab19226cede4cb8e9af21632de0a47b
