### ISSUE TITLE
`unicode` is not a valid type name in Python 3

### ISSUE THREAD

**Issue by telotortium** [defunkt/pystache#209]
See for example: https://github.com/defunkt/pystache/blob/ebdc702f73b1df630a720a5b97d3d882b5a6c8e7/pystache/common.py#L18

**Comment by kerrickstaley** [comment]
As we discussed in https://github.com/kerrickstaley/Chinese-Prestudy/issues/19, the "root cause" is that you're supposed to run `2to3` on the pystache code before installing it in a Python 3 environment. So I'd suggest closing this issue.
