### ISSUE TITLE
Fails test "Nested (Truthy)" from Mustache Spec

### ISSUE THREAD

**Issue by nickretallack** [defunkt/pystache#24]
https://github.com/mustache/spec/blob/master/specs/sections.yml#L123

```
>>> import pystache
>>> pystache.render("| A {{#bool}}B {{#bool}}C{{/bool}} D{{/bool}} E |", {bool:True})
'| A  D E |'
```

**Comment by carlmw** [comment]
Thanks Nick, we're currently working on a version of pystache that builds upon Pieter's work on the spec and his fork of pystache itself. You'll find it at https://github.com/defunkt/pystache/tree/spec-compliant . It's not quite there yet but we hope to have it out there within the next week or so.
