### ISSUE TITLE
Pystache does not render 0

### ISSUE THREAD

**Issue by enaeseth** [defunkt/pystache#3]
The last commit made to Pystache (e38a953b8f3f835756a9c92aac2a073f7a76ef60) stopped rendering `None` and `False` as 'None' and 'False' in templates. This is good, but Pystache now refuses to render all values that evaluate to false, which unfortunately includes `0`.

A fix for this (and associated test) can be found at enaeseth@6e5d57c032218dab2ea84d93ace4a1ffd78ab7e4.

**Comment by defunkt** [comment]
Merged, thanks!
