### ISSUE TITLE
{{#x}}{{#x}}{{/x}}{{/x}} breaks

### ISSUE THREAD

**Issue by holizz** [defunkt/pystache#36]
You cannot work with objects such as the following due to pystache's reliance on regular expressions instead of a grammar:

`{documents: [{name:1, children:[{name: 2, children:[...]}]}]}`

Here's a test case that causes pystache to raise an exception:

http://pastebin.com/4eAYfyKD

**Comment by cjerdonek** [comment]
This is now fixed in the development branch.  Thanks for the report!
