### ISSUE TITLE
Pystache cannot render Unicode strings containing non-ASCII text.

### ISSUE THREAD

**Issue by enaeseth** [defunkt/pystache#4]
In `Template.render_tag`, Pystache converts the value about to be rendered into a string using `str()`. If that value is a Unicode string containing any non-ASCII characters, rendering will fail with a `UnicodeEncodeError`.

enaeseth@f123343cec7afcb22a6227f68229eac57f56ebea is one way of working around this (really quite annoying) problem.

**Comment by defunkt** [comment]
Just merged this in, thanks.

**Comment by falcoa** [comment]
I have the same problem and I do not have any idea how to work around.
Any suggestion????

**Comment by cjerdonek** [comment]
Are you using the newest version?  There is a section on Unicode in the README: https://github.com/defunkt/pystache#unicode

**Comment by falcoa** [comment]
I'm using the pystache version 0.5.4, and python version 2.7

**Comment by cjerdonek** [comment]
See this thread for ideas: https://github.com/defunkt/pystache/issues/168

Try what you see there and reading more, and see if you can figure it out based on that.
