### ISSUE TITLE
Output of callables treated as template code

### ISSUE THREAD

**Issue by jakearchibald** [defunkt/pystache#46]
This is caused by `_render_tags` operating on the output of `_render_sections`

Failing test:

``` python
def test_tag_in_labda_output(self):
    template = '{{#test}}Blah{{/test}}'
    context = {
        'test': lambda x: '{{hello}}'
    }
    ret = pystache.render(template, context)
    self.assertEquals(ret, '{{hello}}')
```

**Comment by jakearchibald** [comment]
As far as I can tell this is a problem for all sections. I guess _render_tags and _render_sections need to be done at the same time sequentially, and the output protected from further rendering.

**Comment by cjerdonek** [comment]
Thanks for the report, test case, and fix!

**Comment by cjerdonek** [comment]
In the process of bringing in some code for a spec-compliant parser, I discovered that this is not actually a bug.  The [spec says here](https://github.com/mustache/spec/blob/9b1bc7ad19247e9671304af02078f2ce30132665/specs/~lambdas.yml#L5) that lambda return values should be interpolated (i.e. interpreted as templates).

Reopening until this is corrected.

**Comment by cjerdonek** [comment]
Fixed in 64cbf12910e37f6253d132c8c6a8e9610f519103

**Comment by jakearchibald** [comment]
Cool, http://mustache.github.com/mustache.5.html needs updated to reflect this.

**Comment by cjerdonek** [comment]
Agreed, it seems like that doc is outdated in a number of respects.  Look at [this issue](https://github.com/mustache/spec/issues/27), for example.

**Comment by cjerdonek** [comment]
Also, I've [updated](https://github.com/defunkt/pystache/tree/development) the pystache README documentation section with a link to the spec and a remark that it is more current than mustache(5).
