### ISSUE TITLE
Silly to string conversion forcing

### ISSUE THREAD

**Issue by daevaorn** [defunkt/pystache#5]
Template's render_unescaped method trying to convert value to string. It breaks when value is not string but unicode or some object convertable to unicode. In the same time render_tag converts value to unicode. I think there is consistency needed. 

Patch:

```
diff --git a/pystache/template.py b/pystache/template.py
index c942cd7..690710e 100644
--- a/pystache/template.py
+++ b/pystache/template.py
@@ -110,7 +110,7 @@ class Template(object):
     @modifier('{')
     def render_unescaped(self, tag_name=None, context=None):
         """Render a tag without escaping it."""
-        return str(context.get(tag_name, ''))
+        return unicode(context.get(tag_name, ''))

     @modifier('>')
     def render_partial(self, tag_name=None, context=None):
```

**Comment by defunkt** [comment]
String conversions now use `unicode()`, are consistent. Closed by 126347153e90d1916d64b6f06eef1b89c5254673
