### ISSUE TITLE
Pystache can't access outer variables in loops

### ISSUE THREAD

**Issue by abentley** [defunkt/pystache#78]
The following fails, but should work (and the equivalent does work with mustache.js)

> > > import pystache
> > > template = "{{#loop}}{{inner}} {{outer}}{{/loop}}"
> > > data = {
> > > ... "loop": [{"inner": "INNER"}],
> > > ... "outer": "OUTER"
> > > ... }
> > > pystache.render(template, data)
> > > u'INNER '

Tested with 0.3.1

**Comment by cjerdonek** [comment]
This should already be fixed in the development branch (and possibly even in master).  See (closed) issue #8, for example.  Can you try there?

**Comment by abentley** [comment]
I can confirm it's fixed in whatever git clone defaults to.

**Comment by cjerdonek** [comment]
Okay, thanks for reporting and confirming, @abentley.  I'm going to close this issue.  Hopefully we'll have a genuine, new release within the next month or so containing all of these fixes (issue #77).
