### ISSUE TITLE
can't see values in 'outer' context  when inside a loop

### ISSUE THREAD

**Issue by rasputnik** [defunkt/pystache#8]
I've got a dead simple template and data structure. 

....amended original comment with inline code and templates,
as it looked godawful.... 

Upshot is: Ruby Mustaches seems to DTRT, Pystache doesn't. Really hope it's a pystache bug :)

**Comment by rasputnik** [comment]
Argh my eyes! 

Sorry. I've stuck the sample code and templates etc up at

http://files.hellooperator.net/pystache-bug.zip

**Comment by defunkt** [comment]
Definitely a bug - thanks for reporting, I'll try to fix soon.

**Comment by rafacv** [comment]
[This commit](http://github.com/rafaelcv/pystache/commit/56c090db370657315e189485459b1b466cc96b1f) fixes the issue of nested contexts.

**Comment by rafacv** [comment]
The above commit has introduced a bug in which inner context propagates its data to outer context.
I [added a test to expose it](http://github.com/rafaelcv/pystache/commit/ee0c747d72632f63e5d30c01fa2a93279593a64a) and [now it's solved](http://github.com/rafaelcv/pystache/compare/ee0c74...6b29bf). :-)

**Comment by rafacv** [comment]
Actually, it proved to be a little more complicated than that.
I realized [inner contexts checking belongs not to examples but to tests](http://github.com/rafaelcv/pystache/commit/6deaadff7e1cf4155ff482e2867e38e94312ca23). Testing the outcome of rendering when a context is passed as a dict object - instead of a View instance - proved my previous solution was flawed.
I came to these [commits](http://github.com/rafaelcv/pystache/compare/6deaad...aa9764) which hopefully solve the issue for good.

**Comment by rasputnik** [comment]
I'm embarassed to say I don't know how to install this and test ....

**Comment by rafacv** [comment]
From source:
    $ wget http://download.github.com/rafaelcv-pystache-v0.3.1-15-gaa97645.zip
    $ unzip rafaelcv-pystache-v0.3.1-15-gaa97645.zip
    $ cd rafaelcv-pystache-aa97645/
    $ nosetests
    $ python setup.py install

In case you have cloned defunkt's repository, try this:
    $ git remote add rafaelcv git://github.com/rafaelcv/pystache.git
    $ git remote update rafaelcv
    $ git checkout rafaelcv/master -b nestedcontexts
    $ nosetests
    $ python setup.py install

**Comment by defunkt** [comment]
Did you forget to commit examples/inner_context_bubbling.py?

**Comment by rafacv** [comment]
Oops, what I forgot was to remove the import. Since I got inner_context_bubbling._pyc_ file in examples directory, import was reaching the thing and tests passed. Sorry about that.

Fixed; overall changes presented in this [compare view](http://github.com/rafaelcv/pystache/compare/4a66a1...217efd).

**Comment by rasputnik** [comment]
Doesn't seem to work (using 217efd4e5f54644648e2e27a25a7a35ad9f396b8).
- the files.hellooperator.net link is working again now, if you want to see what I'm trying to do.

**Comment by rafacv** [comment]
Indeed. Nested contexts were working only for non-looping blocks. [Extended ](http://github.com/rafaelcv/pystache/compare/217efd...55682ac) to looping ones too.
Tests still failing because of [whitespace issue](http://github.com/defunkt/pystache/issues#issue/6) though.

**Comment by cjerdonek** [comment]
Will be taking a look at this.  Here is the test case in the zip file included in one of the [first comments above](https://github.com/defunkt/pystache/issues/8#issuecomment-231512):

Context:

```
{ "greeting": "hello",
  "list": [
    {"name": "eeny"},
    {"name": "meeny"},
    {"name": "miney"},
    {"name": "mo"}
  ]
}
```

Template:

```
Say '{{greeting}}', everyone:

{{#list}}
  {{name}} says: {{ greeting}}
{{/list}}
```

**Comment by cjerdonek** [comment]
This must have gotten fixed somewhere along the way.  Seems to be fixed in master as well.
