### ISSUE TITLE
Pystache version in PyPI is _really_ old (May 2010)

### ISSUE THREAD

**Issue by Tupteq** [defunkt/pystache#83]
It looks like lot of time passed since last PyPI release. I think it's a good idea to release there as often as possible.

**Comment by evandrix** [comment]
Please update the copy at PyPI with the one here at GitHub. I'm working on a project which using this templating engine as well, and would prefer if i could do a simple `pip install`.

reference issue @ http://stackoverflow.com/questions/8908871/how-to-handle-nested-context

**Comment by adiabatic** [comment]
I second this; I'm having the reference issue referred to in evandrix's comment.

**Comment by sean-** [comment]
+1

**Comment by tomekwojcik** [comment]
:+1:

**Comment by lucasb-eyer** [comment]
+1

In the meantime, you can install the github version using:

```
pip install -e git+git://github.com/defunkt/pystache.git#egg=pystache
```

Although it will be reported as version "0.3.1"

**Comment by talos** [comment]
This is because setup.py still has the version set to "0.3.1".  I'm going to fork, fix, and pull that one.  There's no way to push an update to Pypi if the manifest itself is wrong.

Edit: I opened the pull request:

https://github.com/defunkt/pystache/pull/90

**Comment by cjerdonek** [comment]
See also issue #77.

**Comment by talos** [comment]
Understood.  Is it not worth pushing 0.4.0 to Pypi in the interim?

**Comment by tomekwojcik** [comment]
IMHO it is worth pushing newer (but not necessarily the newest) version to PyPI as it'd make deployment of apps depending on Pystache a lot easier.

**Comment by cjerdonek** [comment]
@talos @tomekwojcik Sure, I think you're right.  It's worth pushing 0.4.0 in the interim.  I'll try to do it by this weekend -- assuming I have (and if not, can obtain) the proper permissions.  Thanks for your patience.

**Comment by cjerdonek** [comment]
FYI, yesterday (Saturday) afternoon I sent an e-mail to the current PyPI package index owners asking for PyPI permissions.  I'll let you know when I hear back from one of them.

**Comment by cjerdonek** [comment]
Okay, I have permissions now.  I'll try to take care of this within the next couple days.

**Comment by tomekwojcik** [comment]
@cjerdonek that's great news. Thanks a ton for the effort and :beer: for you :).

**Comment by talos** [comment]
Ditto. Thanks @cjerdonek !

**Comment by cjerdonek** [comment]
Okay, this is [now done](http://pypi.python.org/pypi/pystache/0.4.0).  Let me know if you experience any issues, as this is the first time I've ever uploaded to PyPI.  Also, I've left [v0.3.1](http://pypi.python.org/pypi/pystache/0.3.1) unhidden for now on the main page in case there are any problems with using v0.4.0.

**Comment by talos** [comment]
I was able to obtain and install the new version from PyPI without any problems.  Thanks!

**Comment by cjerdonek** [comment]
Great, thanks for checking @talos and for letting us know.

**Comment by tomekwojcik** [comment]
Thanks for updating Pystache in PIP. All went well for me.
