### ISSUE TITLE
bug in delimiters changing

### ISSUE THREAD

**Issue by bobuk** [defunkt/pystache#84]
I found what changing delimiters with {{= works fine until you don't try to work with nested syntax.
Just try this:

> > > import pystache
> > > print pystache.render("{{#n}} {{test}} {{/n}}", {'n':{'test':'works'}})
> > > works 
> > > print pystache.render("{{=[[ ]]=}} [[#n]] [[test]] [[/n]]", {'n':{'test':'works'}})
> > > Traceback (most recent call last):
> > >   File "test.py", line 3, in <module>
> > >     print pystache.render("{{=[[ ]]=}} [[#n]] [[test]] [[/n]]", {'n':{'test':'works'}})
> > >   File "/Users/bobuk/,misc/pystache/pystache/**init**.py", line 8, in render
> > >     return Template(template, context).render()
> > >   File "/Users/bobuk/,misc/pystache/pystache/template.py", line 172, in render
> > >     result = self._render_tags(template)
> > >   File "/Users/bobuk/,misc/pystache/pystache/template.py", line 113, in _render_tags
> > >     func = self.modifiers[tag_type]
> > > KeyError: '#'

**Comment by lucasb-eyer** [comment]
This issue bothers me too. It also seems to reveal a bug in the reference implementation. Running

```
{{#n}}{{test}}{{/n}}
{{=[[ ]]=}}
[[#n]][[test]][[/n]]
```

in http://mustache.github.com/#demo with the dataset

```
{
  "n": [
    {"test": "works"},
    {"test": "works"},
    {"test": "works"}
  ]
}
```

Shows up

```
worksworksworks
[[#n]][[/n]]
```

While I'd have expected

```
worksworksworks
worksworksworks
```

Or are we misinterpreting the reference documentation here, @defunkt ?

**Comment by cjerdonek** [comment]
This seems to be the same as issue #20 which has already been fixed in the development branch.  See this [test case](https://github.com/defunkt/pystache/blob/32adefb9c06627e228e8fc2de1b4b5cae4f800a5/tests/test_renderengine.py#L404) for example.  I also verified that the test case in the original comment above does work in the development branch:

```
>>> print pystache.render("{{=[[ ]]=}} [[#n]] [[test]] [[/n]]", {'n':{'test':'works'}})
  works 
```
