### ISSUE TITLE
Partials Are HTML escaped if a section is in the template

### ISSUE THREAD

**Issue by bricef** [defunkt/pystache#88]
## Steps to reproduce

Take the following templates:

`partial.mustache`

```
<h2>Hello, I'm a partial. {{a}}</h2>
```

`middle_nosection.mustache`

```
{{> partial }}
hello, I'm the middle without a section
```

`middle_section.mustache`

```
{{> partial }}
hello, I'm the middle with a section
{{#b}}
* {{n}}
{{/b}}
```

run pystache against both templates, and inspect the output:
## Output

```
<h2> Hello, I'm a partial 123 </h2>

hello, I'm the middle without a section
```

For the section:

```
&lt;h2&gt; Hello, I&#39;m a partial 123 &lt;/h2&gt;

hello, I'm the middle with a section
* 1
* 2
```
## Expected

That both partials are rendered the same way (no escaping)

**Comment by bricef** [comment]
Possibly related, lambdas are also escaped before displaying.

**Comment by bricef** [comment]
I narrowed it down to the `literal` function, which, in case markupsafe is installed, escapes html strings.

```
literal = markupsafe.Markup
```

and

```
literal = unicode 
```

turn out to have significantly different meanings.

I've worked round the issue in my code by [forcing `literal` to mean `unicode`](https://github.com/bricef/pystache/commit/1f2dbfcaaf1a0af1b826dc4a86ae0d96a14169e4).

**Comment by cjerdonek** [comment]
Can you try this with the code in the development branch?  Almost all of the issues that have been reported have been fixed there.  I know that references to markupsafe.Markup, for example, have been removed from the code that is currently in the development branch.

**Comment by cjerdonek** [comment]
It looks like this may be a duplicate of issue #53.

**Comment by bricef** [comment]
I can confirm that this works as expected in the development branch. 

```
[11:47][BHAC ~/tmp/pystache.git ]{ master }>
$ python try.py 
<h2> Hello, I'm a partial 123 </h2>

hello, I'm the middle

=====
&lt;h2&gt; Hello, I&#39;m a partial 123 &lt;/h2&gt;

hello, I'm the middle
* 1
* 2


[11:47][BHAC ~/tmp/pystache.git ]{ master }>
$ git checkout development
Switched to branch 'development'
[11:47][BHAC ~/tmp/pystache.git ]{ development }>
$ python try.py 
<h2> Hello, I'm a partial 123 </h2>
hello, I'm the middle

=====
<h2> Hello, I'm a partial 123 </h2>
    hello, I'm the middle
* 1
* 2
```

Closing as fixed in development.

**Comment by cjerdonek** [comment]
Thanks a lot for checking, @bricef.  Hopefully one of us will have time to get the development branch pushed to master and PyPI soon (issue #77).
