### ISSUE TITLE
second list gets all its contents escaped

### ISSUE THREAD

**Issue by drewp** [defunkt/pystache#96]
Using the current git version:

```
>>> pystache.render("{{#p1}}<br>{{/p1}} {{#p2}}<div>{{/p2}}", dict(p1=[1,2], p2=[3,4]))
Markup(u'<br><br> &lt;div&gt;&lt;div&gt;')
```

I was expecting 

```
"<br><br> <div><div>"
```

**Comment by drewp** [comment]
This seems related to https://github.com/defunkt/pystache/issues/88

**Comment by cjerdonek** [comment]
Yes, can you test this in the development branch?

**Comment by cjerdonek** [comment]
I confirmed that the test case above works correctly in the development branch.
