### ISSUE TITLE
Mustache spec v1.1.2 compliance

### ISSUE THREAD

**Issue by rbp** [defunkt/pystache#99]
Pystache (master and development) is currently compliant with Mustache spec 1.0.3. The latest spec version tag is v1.1.2.

I have a branch (from development) which implements v1.1.2 compliance. Namely, it implements dot notation. It also updates the specs submodule to the v1.1.2 tag. All tests are passing.

My branch is located at https://github.com/rbp/pystache/tree/spec-1.1.2-compliant . I am quite new to mustache, so please let me know if I should do a pull request, or if you need further changes. Given that this is a relatively simple (if backwards-incompatible) patch, and one that implements a very handy feature, I'd be glad to see it through.

**Comment by cjerdonek** [comment]
Thanks a lot, @rbp.  And also for asking.  It is fine to do a pull request.  I should be able to process it fairly soon (within a week or so).  I will also let you know if I can recommend any changes.  Thanks.

**Comment by rbp** [comment]
Cool, will do. Thanks :)

**Comment by cjerdonek** [comment]
See issue #100 for further comments.
